import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Icon from './components/icon';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const items = [
  {
    name: "Home",
    path: "/",
    backgroundImage: "/bg-home.jpg",
  },
  {
    name: "Summon Spirit",
    path: "/spiritSummon",
    backgroundImage: "/bg-summon.png",
  },
  {
    name: "New Game",
    path: "/newGame",
    backgroundImage: "/bg-newgame.jpg",
  },
  {
    name: "Settings",
    path: "/settings",
    backgroundImage: "/bg-settings.jpg",
  },
];


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-screen h-screen overflow-y-auto flex bg-gray-100 p-4 justify-center items-center">
          {/* 左邊 layout 區塊 */}
          <div className="max-w-[330px] min-w-[330px] h-full rounded-2xl bg-white flex
          justify-start items-center flex-col overflow-y-auto overflow-x-hidden p-8 mr-4">
            <Icon items={items} />
          </div>
          
        
      
          {children}
          
        </div>
      </body>
    </html>
  );
}
